version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: facebook_worker_postgres
    environment:
      POSTGRES_DB: facebook_worker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d facebook_worker"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: facebook_worker_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: facebook_worker_app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/facebook_worker
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_QUEUE_NAME=facebook_posts
      - FACEBOOK_BASE_URL=https://graph.facebook.com/v18.0
      - FACEBOOK_PAGE_ACCESS_TOKEN=dummy_token
      - FACEBOOK_INBOX_VERIFY_TOKEN=dummy_verify_token
      - DEBUG=true
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data: