version: '3.8'

services:
  postgres:
    image: postgres:15.8
    container_name: facebook-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facebook
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: facebook-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    container_name: facebook-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  rabbitmq_data:
  redis_data: