export enum CampaignWidgetKey {
  TOTAL_ORDERS = 'TOTAL_ORDERS',
  NEW_ORDERS = 'NEW_ORDERS',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID_ORDERS = 'PAID_ORDERS',
  SALES = 'SALES',
  ENGAGED_USERS = 'ENGAGED_USERS',
  UNCONTACTED_INBOX_USERS = 'UNCONTACTED_INBOX_USERS',
  CUSTOMERS_WHO_ORDERED = 'CUSTOMERS_WHO_ORDERED',
  NEW_CUSTOMERS = 'NEW_CUSTOMERS',
  OLD_CUSTOMERS = 'OLD_CUSTOMERS',
}
