version: "3.8"

services:
  # Migration Service
  migration:
    image: postgres:15-alpine
    container_name: vrich_migration
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: vrich_db_dev
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      # แก้ path นี้ให้เป็น absolute path ของเครื่องคุณ
      - ./facebook/migrations:/migrations
    networks:
      - vrich_network_dev
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        sleep 10 &&
        echo 'Testing database connection...' &&
        PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h vrich_db_dev -U ${POSTGRES_USER} -d ${POSTGRES_DB} &&
        echo 'Database is ready! Running migrations...' &&
        for file in /migrations/*.sql; do
          if [ -f \"$file\" ]; then
            echo \"Executing: $file\" &&
            PGPASSWORD=${POSTGRES_PASSWORD} psql -h vrich_db_dev -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f \"$file\" &&
            echo \"Completed: $file\"
          fi
        done &&
        echo 'All migrations completed!'
      "
    profiles: ["migration"]

networks:
  vrich_network_dev:
    external: true
