services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: vrich_app_dev
    environment:
      # Database
      DATABASE_URL: ${DATABASE_URL}

      # App Config
      DEBUG: "True"
      PROJECT_NAME: ${PROJECT_NAME:-VRich Project Dev}
      VERSION: ${VERSION:-1.0.0-dev}
      DESCRIPTION: ${DESCRIPTION:-A VRich project with PostgreSQL (Development)}

      # Security
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}

      # CORS
      ALLOWED_HOSTS_RAW: ${ALLOWED_HOSTS_RAW:-localhost,127.0.0.1,0.0.0.0}

      # API
      API_V1_STR: ${API_V1_STR:-/api/v1}

      # Server
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8000}
      WORKERS: ${WORKERS:-1}

      # File Upload
      UPLOAD_DIR: ${UPLOAD_DIR:-/app/uploads}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      ALLOWED_EXTENSIONS: ${ALLOWED_EXTENSIONS:-jpg,jpeg,png,gif,pdf,doc,docx}

      # Python path
      PYTHONPATH: /app

    volumes:
      # Mount source code for hot reloading
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./tests:/app/tests

    ports:
      - "3010:3010"

    networks:
      - local-network

    restart: unless-stopped

    # Development command with hot reload
    command: uvicorn app.main:socket_app --host 0.0.0.0 --port 3010 --reload --reload-dir /app/app

networks:
  local-network:
    driver: bridge
    name: local-network