### ===== Facebook Health Check =====

### Health check
GET http://localhost:3001/healthcheck


### Admin
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "username": "admin@example.com",
    "password": "adminpass123"
}